package models

import "gorm.io/gorm"

// AutoGenerated 结构体·
type UserInfo struct {
	UserID        string `json:"user_id" gorm:"primaryKey;size:36"` // 用户ID，设置为主键，长度为36
	Username      string `json:"username" gorm:"size:100;unique"`   // 用户名，设置为唯一，长度为100
	Email         string `json:"email" gorm:"size:100;unique"`      // 邮箱，设置为唯一，长度为100
	Password      string `json:"password" gorm:"size:255"`          // 密码，长度为255
	Avatar        string `json:"avatar" gorm:"size:255"`            // 头像，长度为255
	Sex           string `json:"sex" gorm:"size:10"`                // 性别，长度为10
	Bio           string `json:"bio" gorm:"size:500"`               // 个人简介，长度为500
	LastLoginIp   string `json:"last_login_ip" gorm:"size:50"`      // 最后一次登录的IP，长度为50
	LastLoginTime string `json:"last_login_time" gorm:"size:20"`    // 最后一次登录的时间，长度为20
	CreateTime    string `json:"create_time" gorm:"size:20"`        // 注册时间，长度为20
	Status        string `json:"status" gorm:"size:20"`             // 状态，长度为20
	Experience    string `json:"experience" gorm:"size:255"`        // 经验，长度为255
}

func NewUserTable(db *gorm.DB) error {
	//开启自动迁移
	return db.AutoMigrate(&UserInfo{})
}
